"""empty message

Revision ID: 27b9a4a5e01f
Revises: ce103bf53031
Create Date: 2019-05-11 17:23:14.438039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b9a4a5e01f'
down_revision = 'ce103bf53031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_subject',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_type_subject_subject_id_subject')),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name=op.f('fk_type_subject_type_id_type')),
    sa.PrimaryKeyConstraint('type_id', 'subject_id', name=op.f('pk_type_subject'))
    )
    op.create_table('location_subject',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_location_subject_location_id_location')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_location_subject_subject_id_subject')),
    sa.PrimaryKeyConstraint('location_id', 'subject_id', name=op.f('pk_location_subject'))
    )
    op.drop_table('types')
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='fk_locations_location_id_location'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='fk_locations_subject_id_subject'),
    sa.PrimaryKeyConstraint('location_id', 'subject_id', name='pk_locations')
    )
    op.create_table('types',
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='fk_types_subject_id_subject'),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name='fk_types_type_id_type'),
    sa.PrimaryKeyConstraint('type_id', 'subject_id', name='pk_types')
    )
    op.drop_table('location_subject')
    op.drop_table('type_subject')
    # ### end Alembic commands ###
