"""empty message

Revision ID: 2979425e2b5f
Revises: 27b9a4a5e01f
Create Date: 2019-05-11 17:31:23.087142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2979425e2b5f'
down_revision = '27b9a4a5e01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_location_user_id_user'), 'location', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_location_user_id_user'), 'location', type_='foreignkey')
    op.drop_column('location', 'user_id')
    # ### end Alembic commands ###
