"""empty message

Revision ID: 44194fb1a53f
Revises: b8364b16d6af
Create Date: 2019-05-15 14:44:17.320022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44194fb1a53f'
down_revision = 'b8364b16d6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutor', 'hourlyrate',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tutorlocation', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.drop_table('tutorlocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutorlocation', 'id')
    op.alter_column('tutor', 'hourlyrate',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
