"""empty message

Revision ID: 47f8f168767e
Revises: 
Create Date: 2019-05-11 16:45:10.581597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f8f168767e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_index(op.f('ix_city_city'), 'city', ['city'], unique=False)
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_type'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_location_city_id_city')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location'))
    )
    op.create_index(op.f('ix_location_location'), 'location', ['location'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_subject_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    op.create_table('tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phonenumber', sa.String(length=80), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_tutor_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor'))
    )
    op.create_index(op.f('ix_tutor_email'), 'tutor', ['email'], unique=True)
    op.create_index(op.f('ix_tutor_name'), 'tutor', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_name'), table_name='tutor')
    op.drop_index(op.f('ix_tutor_email'), table_name='tutor')
    op.drop_table('tutor')
    op.drop_table('subject')
    op.drop_index(op.f('ix_location_location'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('type')
    op.drop_index(op.f('ix_city_city'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
