"""empty message

Revision ID: ebeefd869c99
Revises: 2979425e2b5f
Create Date: 2019-05-12 12:33:49.748152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebeefd869c99'
down_revision = '2979425e2b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name=op.f('fk_enrollment_type_id_type')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_enrollment_user_id_user'))
    )
    op.create_table('subjectlocation',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_subjectlocation_location_id_location')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_subjectlocation_subject_id_subject'))
    )
    op.create_table('tutorlocation',
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_tutorlocation_location_id_location')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], name=op.f('fk_tutorlocation_tutor_id_tutor'))
    )
    op.drop_table('location_subject')
    op.drop_table('type_subject')
    op.drop_constraint('fk_location_user_id_user', 'location', type_='foreignkey')
    op.drop_constraint('fk_location_tutor_id_tutor', 'location', type_='foreignkey')
    op.drop_column('location', 'tutor_id')
    op.drop_column('location', 'user_id')
    op.drop_constraint('fk_subject_user_id_user', 'subject', type_='foreignkey')
    op.drop_column('subject', 'user_id')
    op.alter_column('tutor', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('tutor', 'phonenumber',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.create_index(op.f('ix_tutor_phonenumber'), 'tutor', ['phonenumber'], unique=True)
    op.drop_constraint('fk_tutor_subject_id_subject', 'tutor', type_='foreignkey')
    op.drop_column('tutor', 'subject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_tutor_subject_id_subject', 'tutor', 'subject', ['subject_id'], ['id'])
    op.drop_index(op.f('ix_tutor_phonenumber'), table_name='tutor')
    op.alter_column('tutor', 'phonenumber',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('tutor', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('subject', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_subject_user_id_user', 'subject', 'user', ['user_id'], ['id'])
    op.add_column('location', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('location', sa.Column('tutor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_location_tutor_id_tutor', 'location', 'tutor', ['tutor_id'], ['id'])
    op.create_foreign_key('fk_location_user_id_user', 'location', 'user', ['user_id'], ['id'])
    op.create_table('type_subject',
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='fk_type_subject_subject_id_subject'),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name='fk_type_subject_type_id_type'),
    sa.PrimaryKeyConstraint('type_id', 'subject_id', name='pk_type_subject')
    )
    op.create_table('location_subject',
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='fk_location_subject_location_id_location'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='fk_location_subject_subject_id_subject'),
    sa.PrimaryKeyConstraint('location_id', 'subject_id', name='pk_location_subject')
    )
    op.drop_table('tutorlocation')
    op.drop_table('subjectlocation')
    op.drop_table('enrollment')
    # ### end Alembic commands ###
