"""empty message

Revision ID: f0723c3de79d
Revises: 47f8f168767e
Create Date: 2019-05-11 17:10:11.903273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0723c3de79d'
down_revision = '47f8f168767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('tutor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_location_tutor_id_tutor'), 'location', 'tutor', ['tutor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_location_tutor_id_tutor'), 'location', type_='foreignkey')
    op.drop_column('location', 'tutor_id')
    # ### end Alembic commands ###
